### ISSUE TITLE
Problema con el tipado de los tramos

### ISSUE THREAD

**Issue by dmonjasm** [dmonjasm/IV#10]
No tengo muy claro que tipo o atributos asignarle a un tramo para que queda completamente claro a que carretera pertenece y en qué trozo de la misma se encuentra el tramo.

**Comment by dmonjasm** [comment]
@marcosrmartin

**Comment by dmonjasm** [comment]
Echale un ojo a los nuevos issues porfa. También estuve bicheando con el código de GO por si quieres echarle un ojo a la rama Objetivo-2.

**Comment by marcosrmartin** [comment]
No hay ningún issue nuevo.

**Comment by marcosrmartin** [comment]
Daniel, yo soy el que tiene que desarrollar de las EDs.

**Comment by dmonjasm** [comment]
> No hay ningún issue nuevo.

Era para que vieras este que cree del tipado de los tramos, que no sabía cómo mencionarte.

**Comment by dmonjasm** [comment]
> Daniel, yo soy el que tiene que desarrollar de las EDs.

Ya me di cuenta ayer 😅. Ya está borrada la rama.
