### ISSUE TITLE
Modelado del problema. 

### ISSUE THREAD

**Issue by marcosrmartin** [dmonjasm/IV#12]
Para completar el Milestone 0 necesitamos crear las distintas entidades y objetos-valores de RouteCheck. Partiendo de #2 y #3 necesitamos calcular el precio de una ruta, la cual será una entidad (llevará a cabo la lógica de negocio), para ello:
1º Definiremos el coste de combustible de nuestro coche.
2º Calcular la distancia y velocidad a lo largo de una ruta para ajustar el consumo.
3º Si una ruta tiene peajes.

**Comment by JJ** [comment]
Esto tiene que estar en el milestone correspondiente, @dmonjasm añádelo.

**Comment by JJ** [comment]
Lo conveniente habría sido sacar más issues de este. Los issues deben ser lo más atómicos posibles. Los mensajes de commits tampoco son muy informativos sobre qué exactamente se ha hecho.
