### ISSUE TITLE
Inicio y fin en tramos.

### ISSUE THREAD

**Issue by marcosrmartin** [dmonjasm/IV#16]
Para ello modelaremos un objeto-valor Posicion, que contenga las coordenadas(latitud, longitud), utilizaremos este formato ya que este no depende de un factor externo (como puede ser una carretera o calle), y con estos se puede calcular directamente la distancia.

**Comment by JJ** [comment]
Ni tú puedes crear una historia de usuario, ni puedes avanzar código directamente con una historia de usuario. Como esto es un issue, debe ir asignado a una historia de usuario (y plantear un problema). Esto parece simplemente una solución para un problema planteado no se sabe bien dónde.

**Comment by dmonjasm** [comment]
Respecto a como representar el inicio y fin de tramos creo que podemos usar en vez de coordenadas el nombre y km de la carretera. Bien en un string o separados en dos atributos. Respecto a lo que hablamos de que podría ser confuso en ciudad realmente no es problemático (creo) porque al tener las calles de una ciudad un nombre único la concatenación de varias calles nos da una ruta única.
