### ISSUE TITLE
Calcular precio ruta

### ISSUE THREAD

**Issue by marcosrmartin** [dmonjasm/IV#18]
Partiendo del #3, el problema que tenemos es como modelizar una ED para calcular el precio de una ruta.

**Comment by marcosrmartin** [comment]
Para poder calcular el precio de una ruta necesitamos conocer los tramos de los que esta compuesta y si esta contiene algún peaje (precio).

**Comment by JJ** [comment]
No veo que aquí se plantee ningún problema cuya solución implique algo llamado "límite".

**Comment by marcosrmartin** [comment]
La única forma que se me ocurre para implicarlo, es explicando que para calcular el coste de una ruta hace falta conocer sus límites de velocidad y distancia de cada uno, pero eso sería una explicación y no tiene lugar en los issues.
