### ISSUE TITLE
Lenguaje de programación.

### ISSUE THREAD

**Issue by marcosrmartin** [dmonjasm/IV#7]
Para solucionar este problema, utilizaría un lenguaje compilado como Rust o Go, ya que para este problema se necesitaría una gran cantidad de cómputo el cual es menor con un lenguaje interpretado.

**Comment by dmonjasm** [comment]
Había pensado utilizar Ruby porque ya tengo experiencia con él, y por otro lado de Rust o Go no tengo ni idea. Aunque me voy a mirar un poco la documentación tanto de Rust como de Go, porque es cierto que va a hacer falta una cierta capacidad de cómputo.

**Comment by dmonjasm** [comment]
He estado mirando documentación de GO y viendo un poco como funcionan los módulos y funciones y creo que podría ir bastante bien. Así que si te parece bien creo que lo voy a hacer con Go.

**Comment by marcosrmartin** [comment]
¡Pues todo dicho! Nos ponemos manos a la obra con el #8. 🤝

**Comment by dmonjasm** [comment]
Cierro ya este issue.

**Comment by dmonjasm** [comment]
Reabro el issue porque no lo cerré con un commit.
