### ISSUE TITLE
Entidades para el producto mínimo viable.

### ISSUE THREAD

**Issue by marcosrmartin** [dmonjasm/IV#8]
Para conseguir la funcionalidad mínima de la aplicación creo que se podrían definir los siguientes objetos-valores:
- Coche / Consumo.
- Peaje.
- Tramo.

Y en cuanto a entidad, una entidad Ruta, que será la encargada de llevar a cabo la lógica de negocio teniendo en cuenta los objetos anteriores.

**Comment by dmonjasm** [comment]
Yo lo veo correcto. De todas formas como me tengo que poner a investigar un poco sobre Go una vez tenga una idea un poco más general de como funcionan en Go las clases/módulos podemos ver si este enfoque inicial se ajusta bien.

**Comment by dmonjasm** [comment]
Cierro este issue.

**Comment by dmonjasm** [comment]
Reabro el issue por la misma razón que reabro #7
