### ISSUE TITLE
[ED] Objetos-valores

### ISSUE THREAD

**Issue by marcosrmartin** [dmonjasm/IV#9]
El primer objeto-valor es *Tramo*, este lo entiendo como un trozo de recorrido a la misma velocidad, creo que se podría estructurar de la siguiente forma:
- Inicio.
- Fin.
- Distancia.
- Peaje(s).
- Límite velocidad.

El objeto *Peaje* se estructuraría así:
- Precio(s) *Si el precio varía según el tipo de vehículo u otro parámetro*

Por último el objeto-valor *coche*:
- Tipo (Gasolina, gasoil, híbrido, eléctrico).
- Consumo(s).

Coméntame que opinas y discutimos posibles cambios.

**Comment by dmonjasm** [comment]
Respecto al objeto-valor tramo no tengo muy claro como guardar el inicio y el final, pues si los guardo como el número de kilómetro de una carretera determinada podría ahorrarme el atributo distancia ya que lo podría calcular a partir de lo anterior. Por otro lado me gustaría también almacenar a que carretera(s) pertenece cada tramo.

El objeto peaje lo veo perfecto y efectivamente el precio es variable en función del tramo del que se proceda, del tipo de vehículo de la hora y en algunos casos de la época del año.

Y por último al objeto valor coche le pondría un atributo más que indique si se trata de un vehículo ligero o un vehículo pesado, que es la distinción que se considera en los precios de los peajes.

Dime que te parece y arreglamos lo que haga falta.

**Comment by marcosrmartin** [comment]
Creo que a lo mejor renta guardar la distancia porque es un dato que vas a tener que calcular para cualquier operación, aun así guardaría de todas formas el inicio y fin con el km de la carretera a la que pertenece como has dicho. 
Dejando de lado este atributo ya que las dos formas son válidas, creo que para *Tramo* se podría añadir un atributo **Carretera**, ya que un tramo solo puede estar en una carretera, pero al incluir este atributo me surge la duda de si la aplicación también tendría que funcionar en ciudad, y si la respuesta es que sí, como almacenaríamos los tramos en esta, ¿Por calles, cruces entre calles, números?

**Comment by dmonjasm** [comment]
Creo que tienes razón, sería demasiado gasto de tiempo calcular la distancia de cada tramo cada vez.
Respecto a como almacenarlo veo bien en ponerle un atributo carretera que indique el nombre/código de la carretera así como guardar el punto de inicio (km de inicio) y el punto de final (km de final) de un tramo (ya que entre dos kilómetros podría bifurcarse un tramo o haber un cambio de la velocidad).

Respecto a que funcione en ciudad, sí la aplicación debería funcionar también en ciudad y en este caso como las carreteras de ciudad no suelen estar numeradas se trataría el nombre de la calle (a esto todavía le tengo que dar alguna vuelta).

**Comment by marcosrmartin** [comment]
Si se hace en ciudad la complejidad de la aplicación se dispara, habría que tener en cuenta también todos los sentidos de las calles, además de diferentes niveles por puentes y túneles, diferentes velocidades, todos los cruces entre calles. Por lo que entonces tendría más sentido poner como inicio y fin, coordenadas que no dependen de la carretera.

**Comment by dmonjasm** [comment]
Cierto es. Tengo que ver como voy a hacer el cálculo de distintas rutas pero creo que ese punto ya queda fuera de este objetivo 2 porque ya tendría que ver un poco con detalles de implementación.

**Comment by marcosrmartin** [comment]
Si, ya estaría fuera de este punto, pero yo tengo que crear las ED y necesito saber si tengo que implementar alguno de esos atributos para encajarlos en las EDs que más le convengan. Dale una vuelta y coméntame si le añadimos más atributos.

**Comment by dmonjasm** [comment]
He subido lo que prodría ser una primera definición de las entidades y los objetos valor. Echale un ojo y me dices.
